4 complete accountdefinitionapi implementation
TomeQ2k/2022_TAB_S13_NOWOK pull request #12
Opened 2022-04-13 10:34 UTC by karolkadlubowski

PR flp nie hejtuj

2022-04-13 11:14 UTC, TomeQ2k commented on src/Services/AccountDefinition.API/tests/AccountDefinition.API.Tests.Unit/Application/Services/AccountProviderServiceTests.cs
> +                .ReturnsAsync(0);
You can change 0 to default

2022-04-13 11:48 UTC, filippyziak commented on src/Services/AccountDefinition.API/src/AccountDefinition.API.Application/Services/AccountProviderService.cs
> +            _logger.Info($"{accountProviders.Count} account types fetched from the database");
```suggestion
            _logger.Info($"{accountProviders.Count} account providers fetched from the database");
```

2022-04-13 11:48 UTC, filippyziak commented on src/Services/AccountDefinition.API/src/AccountDefinition.API/Controllers/AccountProviderController.cs
> +
remove this line
```suggestion
```

2022-04-13 11:49 UTC, filippyziak requested changes
as in comments

2022-04-15 07:20 UTC, TomeQ2k approved these changes

2022-04-15 09:13 UTC, merged