11 design implementation of identityapi
TomeQ2k/2022_TAB_S13_NOWOK pull request #34
Opened 2022-06-15 17:03 UTC by filippyziak

2022-06-15 20:09 UTC, TomeQ2k requested changes
- Make requested changes
- REMOVE CHANGES FOR FILE VENUE.API INIT.SQL SCRIPT
- Remove unused folders
- Write healthcheck for database connection in API layer
- remove unit tests project if its not used

2022-06-15 20:09 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Application/Features/ChangeUserEmail/ChangeUserEmailCommandHandler.cs
> +                throw new DatabaseOperationException($"Error while updating user #{user.UserId}");
```suggestion
                throw new DatabaseOperationException($"Error while changing email for user #{user.UserId}");
```

2022-06-15 20:09 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Application/Features/ChangeUserPassword/ChangeUserPasswordCommandHandler.cs
> +                throw new DatabaseOperationException($"Error while updating user #{user.UserId}");
```suggestion
                throw new DatabaseOperationException($"Error while updating password for user #{user.UserId}");
```

2022-06-15 20:09 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Application/Features/SigninUser/SigninUserCommandHandler.cs
> +            _logger.Info($"jwt token has been generated for #{user.UserId}");
```suggestion
            _logger.Info($"JWT token has been generated for #{user.UserId}");
```

2022-06-15 20:09 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Domain/Configuration/ServiceConfiguration.cs
> +        public JwtConfig JwtConfig { get; set; }
```suggestion
        public DatabaseConfig DatabaseConfig { get; init; }
        public JwtConfig JwtConfig { get; init; }
```

2022-06-15 20:09 UTC, TomeQ2k commented on src/Services/Venue.API/_Scripts/Database/init.sql
> -CREATE TABLE IF NOT EXISTS "Venue"."Locations"
Why you override this file!?

2022-06-15 20:26 UTC, filippyziak commented on src/Services/Venue.API/_Scripts/Database/init.sql
> -CREATE TABLE IF NOT EXISTS "Venue"."Locations"
XDDDD

2022-06-15 20:29 UTC, filippyziak commented on src/Libraries/Library.Shared.Models/Identity/Events/UserEmailChangedEvent.cs
> +        public UserEmailChangedEvent() => EventType = EventType.USER_CREATED;
XDDDD

2022-06-15 20:38 UTC, filippyziak commented on src/Services/Identity.API/src/Identity.API.Application/Services/JwtAuthTokenService.cs
> +            return jwtTokenHandler.WriteToken(token);
?

2022-06-15 20:41 UTC, filippyziak commented on src/Services/Identity.API/src/Identity.API/Controllers/IdentityController.cs
> +        }
why?

2022-06-15 20:42 UTC, filippyziak commented on src/Services/Venue.API/_Scripts/Database/init.sql
> -CREATE TABLE IF NOT EXISTS "Venue"."Locations"
i really don't know how that happened

2022-06-15 21:00 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Application/Services/JwtAuthTokenService.cs
> +            return jwtTokenHandler.WriteToken(token);
I remember sth that there was the async overload of this method

2022-06-15 21:01 UTC, TomeQ2k commented on src/Services/Venue.API/_Scripts/Database/init.sql
> -CREATE TABLE IF NOT EXISTS "Venue"."Locations"
me too

2022-06-15 21:03 UTC, TomeQ2k commented on src/Services/Identity.API/src/Identity.API.Infrastructure/Database/Repositories/IdentityRepository.cs
> +        public async Task<UserPersistenceModel> FindUserAsync(string email)
```suggestion
            => await _identityDbContext.Users.FirstOrDefaultAsync(u => u.UserId == userId);

        public async Task<UserPersistenceModel> FindUserAsync(string email)
```

2022-06-15 21:03 UTC, TomeQ2k commented on src/Services/Venue.API/_Scripts/Database/init.sql
> +CREATE SCHEMA IF NOT EXISTS "Venue";
```suggestion
CREATE SCHEMA IF NOT EXISTS "Venue";
```

2022-06-16 08:54 UTC, filippyziak commented on src/Services/Identity.API/src/Identity.API.Application/Services/JwtAuthTokenService.cs
> +            return jwtTokenHandler.WriteToken(token);
I couldn't Find it maybe not in this class

2022-06-16 09:11 UTC, merged